// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "portfolio-blog/views/components"

func Index() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<!doctype html><html lang=\"en\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Header("Xtasy Sensei").Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<body><div class=\"grid-2\"><div class=\"section-1\"><img src=\"/static/assets/xtc.jpeg\" alt=\"Profile Picture\" class=\"profile-pic\"><h2>Shem Maiwuya</h2><h2><a href=\"/admin-login\">Xtasy Sensei</a></h2><p>Jos,Nigeria.</p><a href=\"https://x.com/9shem6\"><i class=\"fab fa-twitter\"></i></a> <a href=\"https://linkedin.com/in/shem-maiwuya-328977304\"><i class=\"fab fa-linkedin\"></i></a> <a href=\"https://github.com/xtasysensei/\"><i class=\"fab fa-github\"></i></a><div><button class=\"blog-button\"><a href=\"/show-blogs\">Read My Blogs</a></button></div></div><div class=\"section-2\"><h2>About</h2><p>A budding Backend and Devops Engineer. Also enjoys testing linux distros on virtual machines</p><h2>Experience</h2><p>Worked on a few personal projects in Python, Go, Php and Javascript</p><h2>Skills</h2><p>Go developer. Intermediate python developer.Little bit of Php knowledge. Bash scripting. Knowledge on version control with Git and Github</p><h2>Projects</h2><a href=\"https://github.com/xtasysensei/php-projects\">Form validation(php)</a> <a href=\"https://github.com/xtasysensei/text-adventure\">text adventure game(python)</a> <a href=\"https://github.com/xtasysensei/wallet-phrase-manager\">wallet phrase manager(WIP. python)</a><h2>Goals</h2><p>Improve my Go skills by creating microservices</p><p>Become a better Devops Engineer by using various tools for deployment and containerization</p><h2>Contact</h2><p>maiwuyashem@gmail.com</p><a href=\"/create-admin\">create admin</a></div></div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
